<?php
$viewModel = $this->viewModel()->getCurrent();
$icon = $viewModel->getVariable('icon');
?>
<div class="page-head">
    <div class="container-fluid">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1><i class="fa <?= $viewModel->getVariable('icon') ?>"></i> <?= $viewModel->getVariable('title', 'Read entity') ?></h1>
        </div>
        <!-- END PAGE TITLE -->
        <?=$this->pageToolbar?>
    </div>
</div>
<div class="page-content">
    <div class="container-fluid">
        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="page-content-inner">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light ">
                        <div class="portlet-title">
                            <div class="caption">
                                <span class="caption-subject bold"><?= $viewModel->getVariable('subject', 'Read entity') ?></span>
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <?= $this->form ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>