<?php
/** @var \AdminV2\Application\ViewModel\SortViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$orderRow = $viewModel->getVariable('orderRow');
$defaultSort = $viewModel->getVariable('defaultSort');
$criteria = $viewModel->getVariable('validCriteria');
$sort = '';//$viewModel->getSort();

if (!empty($criteria['order'])) {
    if ($criteria['order'] == $orderRow . ' asc') {
        $icon = 'fa-sort-amount-asc';
    } else if ($criteria['order'] == $orderRow . ' desc') {
        $icon = 'fa-sort-amount-desc';
    } else {
        $icon = 'fa-sort';
    }
} else if ($defaultSort) {
    $icon = 'fa-sort-amount-desc';
} else {
    $icon = 'fa-sort';
}
?>

<th width="<?= $viewModel->getVariable('width') ?>"
    id="<?= $orderRow ?>-sort"
    class="sorting bg-default bg-font-default text-<?= $viewModel->getVariable('align', 'left') ?>">
    <strong><?= $viewModel->getVariable('value') ?></strong>
    <div class="pull-right"><i class="fa <?= $icon ?> font-dark"></i></div>
</th>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $("#"+"$orderRow"+"-sort").click(function() {
        window.location.href = "$sort";
    });
});
JS;
$this->inlineScript()->captureEnd() ?>
