<?php
/** @var \TestCase\ViewModel\SitesTestsViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$testsBySites = $viewModel->getAllCases();
?>

<div class="portlet light ">
    <div class="portlet-title">
        <div class="caption caption-md">
            <i class="icon-bar-chart font-red"></i>
            <span class="caption-subject font-red bold uppercase">Sites tests</span>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row number-stats margin-bottom-30">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="stat-left">
                    <div class="stat-number">
                        <div class="title"> Total </div>
                        <div class="number"> <?=array_sum($testsBySites)?> </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="stat-right">
                    <div class="stat-number">
                        <div class="title"> New (for last 7 days) </div>
                        <div class="number"> <?=$viewModel->getNewCases()?> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-scrollable table-scrollable-borderless">
            <table class="table table-hover table-light">
                <thead>
                <tr>
                    <th> Site </th>
                    <th class="text-right"> Tests </th>
                </tr>
                </thead>
                <?php foreach ($testsBySites as $site=>$testsCount): ?>
                    <tr>
                        <td><?=$site?></td>
                        <td class="text-right"><?=$testsCount?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
