<?php
/** @var \Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}
$options = $viewModel->getVariable('options');
$name = $viewModel->getVariable('name');
$value = $viewModel->getVariable('value');
if (is_null($value)) {
    $value = $viewModel->getVariable('defaultValue');
}
$disabled = $viewModel->getVariable('disabled') ? 'disabled' : '';
$errors = $viewModel->getVariable('errors', []);
?>
<div class="form-group <?= (!empty($errors)) ? 'has-error' : ''; ?>">
    <label class="col-md-3 control-label"><?=$label?></label>
    <div class="col-md-5">
        <div class="radio-list">
            <?php foreach ($options as $optionValue => $option): ?>
                <label>
                    <?php if ($optionValue == $value):?>
                        <input name="<?=$name?>" value="<?=$optionValue?>" type="radio" checked <?=$disabled?>>
                    <?php else: ?>
                        <input name="<?=$name?>" value="<?=$optionValue?>" type="radio" <?=$disabled?>>
                    <?php endif; ?>
                    <?= $option ?>
                </label>
            <?php endforeach; ?>
        </div>
        <?php if (!empty($errors)): ?>
            <?php if (is_array($errors)): ?>
                <p class="help-block"><?=implode('<br/> ', $errors);?></p>
            <?php else: ?>
                <p class="help-block"><?=$errors?></p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
