<?php
$this->headLink()->appendStylesheet('/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css');
$this->headScript()->appendFile('/plugins/moment.min.js');
$this->headScript()->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js');

/** @var \Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$errors = $viewModel->getVariable('errors', []);
$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}
$name = $viewModel->getVariable('name');
$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}
$value = $viewModel->getVariable('value');
$class = $viewModel->getVariable('class');
$disabled = '';
$disabled = $viewModel->getVariable('disabled');
if ($disabled) {
    $disabled = 'disabled=""';
}
$readonly = $viewModel->getVariable('readonly');
if ($readonly) {
    $readonly = 'readonly=""';
}
$dateStartDate = $viewModel->getVariable('date-start-date');
$inputWidthClass = $viewModel->getVariable('input-width-class', 'col-md-5');
?>
<div class="form-group <?= (!empty($errors)) ? 'has-error' : ''; ?>">
    <label class="col-md-3 control-label"><?= $label ?></label>
    <div class="<?=$inputWidthClass?>">
        <input type="text"
               name="<?=$name?>"
               id="<?=$name?>-control"
               class="form-control <?=$class?> date-picker"
               data-date-format="yyyy-mm-dd"
               <?php if ($dateStartDate) echo "data-date-start-date='$dateStartDate'"?>
               <?=$readonly?>
               <?=$disabled?>
               placeholder="<?= $placeholder ?>"
               value="<?=$value?>">

        <?php if (!empty($errors)): ?>
            <?php if (is_array($errors)): ?>
                <span class="help-block"><?=implode('<br/> ', $errors);?></span>
            <?php else: ?>
                <span class="help-block"><?=$errors?></span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?= $this->linkToLog ?>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $('#$name-checkbox').click(function() {
        if ($('#$name-control').attr('disabled')) {
            $('#$name-control').removeAttr('disabled');
        } else {
            $('#$name-control').attr('disabled', 'disabled');
            $('#$name-control').val('');
        }
    });
    
    $('.date-picker').datepicker({
        rtl: App.isRTL(),
        orientation: "left",
        autoclose: true
    });
});
JS;
$this->inlineScript()->captureEnd() ?>