<?php
/** @var \Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$errors = $viewModel->getVariable('errors', []);
$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}
$name = $viewModel->getVariable('name');
$help = $viewModel->getVariable('help');
$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}
$value = $viewModel->getVariable('value');
$class = $viewModel->getVariable('class');
$rows = $viewModel->getVariable('rows', 3);
$disabled = '';
$disabled = $viewModel->getVariable('disabled');
if ($disabled) {
    $disabled = 'disabled=""';
}
$readonly = $viewModel->getVariable('readonly');
if ($readonly) {
    $readonly = 'readonly=""';
}
$areaWidthClass = $viewModel->getVariable('areaWidthClass', 'col-md-5');
?>
<div class="form-group <?= (!empty($errors)) ? 'has-error' : ''; ?>">
    <label class="col-md-3 control-label"><?= $label ?></label>
    <div class="<?=$areaWidthClass?>">
        <textarea name="<?=$name?>"
               class="form-control <?=$class?>"
               <?=$readonly?>
               <?=$disabled?>
               placeholder="<?= $placeholder ?>"
               rows="<?=$rows?>"><?=$value?></textarea>
        <?php if ($help): ?>
            <span class="help-inline"><?=$help?></span>
        <?php endif; ?>
        <?php if (!empty($errors)): ?>
            <?php if (is_array($errors)): ?>
                <span class="help-block"><?=implode('<br/> ', $errors);?></span>
            <?php else: ?>
                <span class="help-block"><?=$errors?></span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?= $this->linkToLog ?>
</div>
