<?php
/** @var \Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$method =  $viewModel->getVariable('method', 'get');
$action = '';
if ($viewModel->getVariable('actionRoute')) {
    $action = $this->url(
        $viewModel->getVariable('actionRoute'),
        $viewModel->getVariable('actionRouteOptions', [])
    );
}
$enctype = $viewModel->getVariable('enctype', 'application/x-www-form-urlencoded');
$elementsViews = $viewModel->getChildrenByCaptureTo('form-element');
$buttonsViews = $viewModel->getChildrenByCaptureTo('form-button');

$validCriteria = $viewModel->getVariable('validCriteria');
$limit = isset($validCriteria['limit']) ? $validCriteria['limit'] : 20;

?>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-magnifier"></i>
            <span class="caption-subject bold uppercase">Filter</span>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form class="form-horizontal" method="<?= $method ?>" action="<?= $action ?>" enctype="<?= $enctype ?>">
            <div class="form-body">
                <div class="row">
                    <?php foreach ($elementsViews as $view): ?>
                        <div class="col-md-6">
                            <?= $this->render($view); ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <input type="hidden" name="limit" value="<?= $limit ?>">

            <div class="form-actions">
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <?= $this->{'form-button'}; ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"> </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>