<!-- BEGIN HEADER MENU -->
<div class="page-header-menu">
    <div class="container-fluid">
        <!-- BEGIN MEGA MENU -->
        <div class="hor-menu">
            <ul class="nav navbar-nav">
                <li class="menu-dropdown classic-menu-dropdown ">
                    <a href="/">Dashboard</a>
                </li>
                <li class="menu-dropdown classic-menu-dropdown ">
                    <a href="<?=$this->url('TestRun-list')?>">Test Runs</a>
                </li>
                <li class="menu-dropdown mega-menu-dropdown ">
                    <a href="<?=$this->url('TestCase-list')?>">Test Cases</a>
                </li>
                <li class="menu-dropdown mega-menu-dropdown ">
                    <a href="<?=$this->url('UseCase-list')?>">Use Cases</a>
                </li>
                <li class="menu-dropdown mega-menu-dropdown ">
                    <a href="<?=$this->url('Sites-list')?>">Sites</a>
                </li>
                <li class="menu-dropdown mega-menu-dropdown ">
                    <a href="<?=$this->url('TestCase-diff')?>"> Cases diff</a>
                </li>
                <li class="menu-dropdown mega-menu-dropdown ">
                    <a href="<?=$this->url('Workers-list')?>"> Workers</a>
                </li>
                <li class="menu-dropdown classic-menu-dropdown ">
                    <a href="javascript:;"> Settings
                        <span class="arrow"></span>
                    </a>
                    <ul class="dropdown-menu pull-left">
                        <li class=" ">
                            <a href="<?=$this->url('Users-list')?>" class="nav-link">
                                <i class="fa fa-users"></i> Users
                            </a>
                        </li>
                        <li class=" ">
                            <a href="#" class="nav-link">
                                <i class="fa fa-eye"></i> Permissions
                            </a>
                        </li>
                        <li class=" ">
                            <a href="#" class="nav-link">
                                <i class="fa fa-envelope-o"></i> Notifications
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- END MEGA MENU -->
    </div>
</div>
<!-- END HEADER MENU -->